### ISSUE TITLE
Illegal space before opening round brace

### ISSUE THREAD

**Issue by ts-ign0re** [addyosmani/sublime-fixmyjs#6]
Hi, great plugin. Bu it does not correct the extra space after the function declaration.
![steroids ios-sim 146x30 2014-10-11 10-02-21](https://cloud.githubusercontent.com/assets/4414123/4601604/537f1048-510c-11e4-939d-abc95c0241e2.jpg)

**Comment by jesperronn** [comment]
@nashpro do you have a link to the upstream bug? I am struggling with this problem and looking for a fix :)

**Comment by jesperronn** [comment]
Aah I found it. https://github.com/jshint/fixmyjs/issues/110 solves the issue (version 2 of fixmyjs)
